site_name: Keycloak Auth Proxy
site_url: https://omar-massfih.github.io/keycloak-auth-proxy/
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep-purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate

repo_url: https://github.com/omar-massfih/keycloak-auth-proxy
repo_name: omar-massfih/keycloak-forward-auth
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Configuration:
      - Environment Variables: configuration/env.md
  - Deployment:
      - Container: deployment/container.md
      - OpenShift: deployment/openshift.md
      - Kubernetes: deployment/kubernetes.md
  - API Reference:
      - Endpoints: api/endpoints.md
  - Contributing: contributing.md
  - License: license.md
